### PR TITLE
DEV: add functions-time corr, att, speck,xf,dev

### PR DESCRIPTION
**Pull request by yugangzhang**
Add new functions, including new time correlation functions, speckle visibility analysis, modified xfuncs, and some developed function during 2015 winter.

### CODE REVIEW

**Comment by sameera2004** [comment]
@yugangzhang Thankyou. However, some of these functions already implemented in skbeam.  Like multi tau one time correlation, removing bad images,  two time correlation , xsvs, fitting functions for xsvs etc... Tomorrow, we will discuss about getting the functions that is not in skbeam and clean/update the pipelines.

**Comment by yugangzhang** [comment]
Good idea.

**Comment by sameera2004** [comment]
@yugangzhang did you need all these functions to merge?
 Because it contain classes like `class LazyEigerHandler(HandlerBase)` which are already in chxtools

**Comment by yugangzhang** [comment]
@sameera2004  thanks, but don't worry, we will not use that LazyEiger... things from chxtools.

**Pull request merged**
