### PR TITLE
update chxtools

### PR DESCRIPTION
**Pull request by yugangzhang**
--> Remove unnecessary packages in requirement.txt
--> Remove data analysis files: speckle/two-time because they are already in pyCHX

### CODE REVIEW

**Comment by yugangzhang** [comment]
@mrakitin can you take a look? Thx!

**Review by mrakitin — COMMENTED** [review]
Thanks for the update! I think the dependencies can just be removed rather than commenting out. Please sort the requirements in the file alphaberically.

**Comment by yugangzhang** [comment]
Thanks! I sorted it.

**Comment by mrakitin** [comment]
Not sure, `eiger-io` still goes last.

**Comment by yugangzhang** [comment]
Please see

https://github.com/NSLS-II-CHX/chxtools/blob/master/requirements.txt

I changed it.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mrakitin** [comment]
Oh, I see. I thought it was done within this PR, but it came from the direct commit to master in https://github.com/NSLS-II-CHX/chxtools/commit/94b6338cd6a7913decf41354e3b4b34e0638cfcd.

**Comment by mrakitin** [comment]
This info may be useful to learn more about branches, etc: https://github.com/NSLS-II/bluesky/blob/master/.github/CONTRIBUTING.md.

**Pull request merged**
