### PR TITLE
Add support for files generated by newer firmware

### PR DESCRIPTION
**Pull request by brunoseivam**
The newest Eiger firmware changes the way the HDF5 files are organized. Data file pointers in the master file are now within a group called 'data'.

### CODE REVIEW

**Comment by ericdill** [comment]
Awesome, thank you for doing this!  @yugangzhang can you confirm that this works before I merge it?

**Comment by ericdill** [comment]
Thanks @brunoseivam @yugangzhang

**Comment by ericdill** [comment]
It might be useful to add some state to this pims reader that keeps track of what format the data file is

**Comment by yugangzhang** [comment]
sure. I will document all the details for the new data structures and how we fix the problems.

Sent from my iPhone

On Jul 28, 2015, at 10:41 AM, Eric Dill <notifications@github.com<mailto:notifications@github.com>> wrote:

It might be useful to add some state to this pims reader that keeps track of what format the data file is

**Comment by yugangzhang** [comment]
```

A procedure for opening new Egier h5 file.

source activate ophyd
conda install chxtools  #install the latest chxtools
export HDF5_PLUGIN_PATH=/nfs/xf11id/mc/envs/ophyd/lib  #initially  this path is wrong.

```

**Pull request merged**
